//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanQuanAo_Main_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProDetail
    {
        public ProDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int IDSup { get; set; }
        public int IDColor { get; set; }
        public int IDSize { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> RemainQuantity { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<int> ViewQuantity { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
