//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanQuanAo_Main_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.ProDetails = new HashSet<ProDetail>();
        }
    
        public int IDSup { get; set; }
        public string NameSup { get; set; }
        public string AddressSup { get; set; }
    
        public virtual ICollection<ProDetail> ProDetails { get; set; }
    }
}
